### ISSUE TITLE
French Toast score not counting "French Toast"

### ISSUE THREAD

**Issue by Minotaurinmaze** [colorfulFlames/flames#26]
**Describe the bug**
Flames' French Toast score only counts up when french toast is typed in lower case. Writing "French Toast" will not bring up the score despite the user talking about french toast.

**To Reproduce**
1. Type "/mydata"
2. Click "Fun Fact"
3. Note the score
4. Type "French Toast"
5. Type "/mydata"
6. Click "Fun Fact"
7. The score will have not gone up
9. Type "french toast"
10. Type "/mydata"
11. Click "Fun Fact"
12. The score will have gone up now

**Expected behavior**
The user's french toast score will go up even if french toast is typed capitalized.

**Screenshots**
![image](https://user-images.githubusercontent.com/65237985/136825107-28e93b19-547a-4dc3-a1cc-65b9798731e4.png)
![image](https://user-images.githubusercontent.com/65237985/136825146-14d9595b-2696-4b66-8b04-2e54ea1669b0.png)

**Client**
Upstream version of Flames

**Additional context**
French toast 😬😬😩

**Comment by SeveralCircles** [comment]
Thanks for reporting this.
